#!/usr/bin/env bash
# setup.sh — first-time server setup for Crash Site
#
# Usage:
#   ./scripts/setup.sh
#
# What it does:
#   1. Checks prerequisites (git, docker, nginx, certbot)
#   2. Prompts for all required configuration values
#   3. Writes .env
#   4. Creates runtime directories (data/, uploads/, backups/)
#   5. Configures nginx with your domain
#   6. Builds and starts Docker containers
#   7. Optionally requests an SSL certificate via Certbot

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

cd "$ROOT_DIR"

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; RESET='\033[0m'

info()    { echo -e "${GREEN}[setup]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[warn]${RESET}  $*"; }
err()     { echo -e "${RED}[error]${RESET} $*" >&2; }
require() {
  if ! command -v "$1" &>/dev/null; then
    err "Required tool not found: $1"
    echo "  Install it and re-run setup."
    exit 1
  fi
}

echo ""
echo "================================================"
echo "  Crash Site — first-time setup"
echo "================================================"
echo ""

# ── 1. Prerequisites ─────────────────────────────────────────────────────────
info "Checking prerequisites..."
require git
require docker

if ! docker compose version &>/dev/null 2>&1; then
  err "docker compose (v2) not found. Install the Docker Compose plugin."
  exit 1
fi

NGINX_AVAILABLE=true
CERTBOT_AVAILABLE=true
command -v nginx   &>/dev/null || NGINX_AVAILABLE=false
command -v certbot &>/dev/null || CERTBOT_AVAILABLE=false

[ "$NGINX_AVAILABLE"  = false ] && warn "nginx not found — skipping nginx configuration"
[ "$CERTBOT_AVAILABLE" = false ] && warn "certbot not found — SSL setup will be skipped"

# ── 2. Check .env ─────────────────────────────────────────────────────────────
if [ -f "$ROOT_DIR/.env" ]; then
  warn ".env already exists."
  read -r -p "  Overwrite it? [y/N] " OVR
  if [[ "$OVR" != "y" && "$OVR" != "Y" ]]; then
    echo "  Keeping existing .env."
    WRITE_ENV=false
  else
    WRITE_ENV=true
  fi
else
  WRITE_ENV=true
fi

# ── 3. Collect config ─────────────────────────────────────────────────────────
if [ "$WRITE_ENV" = true ]; then
  echo ""
  echo "--- Configuration ---"
  echo "  Leave a field blank to accept the default shown in [brackets]."
  echo ""

  read -r -p "Domain (e.g. crashsite.app): " DOMAIN
  if [ -z "$DOMAIN" ]; then
    err "Domain is required."
    exit 1
  fi

  read -r -p "GitHub OAuth Client ID: " GH_ID
  read -r -p "GitHub OAuth Client Secret: " GH_SECRET
  read -r -p "Google OAuth Client ID (leave blank to disable): " G_ID
  read -r -p "Google OAuth Client Secret (leave blank to disable): " G_SECRET

  # Generate a random JWT secret if none provided
  DEFAULT_JWT="$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 64)"
  read -r -p "JWT secret [auto-generated]: " JWT_INPUT
  JWT_SECRET="${JWT_INPUT:-$DEFAULT_JWT}"

  PROTOCOL="https"

  cat > "$ROOT_DIR/.env" <<EOF
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Keep this file secret — never commit it to git.

AUTH_JWT_SECRET=${JWT_SECRET}
# Set after first login — see: ./scripts/make-admin.sh
ADMIN_SOCIAL_IDS=

PORT=4000
NODE_ENV=production

CORS_ORIGIN=${PROTOCOL}://${DOMAIN}
OAUTH_CALLBACK_BASE=${PROTOCOL}://${DOMAIN}
FRONTEND_URL=${PROTOCOL}://${DOMAIN}
SITE_URL=${PROTOCOL}://${DOMAIN}

GITHUB_CLIENT_ID=${GH_ID}
GITHUB_CLIENT_SECRET=${GH_SECRET}
GOOGLE_CLIENT_ID=${G_ID}
GOOGLE_CLIENT_SECRET=${G_SECRET}

VITE_API_URL=${PROTOCOL}://${DOMAIN}/api
EOF

  chmod 600 "$ROOT_DIR/.env"
  info ".env written (permissions: 600)"
else
  # Read domain from existing .env for nginx setup
  DOMAIN="$(grep -E '^(SITE_URL|FRONTEND_URL)=' "$ROOT_DIR/.env" | head -1 | sed 's|.*://||' | tr -d '"')"
fi

# ── 4. Runtime directories ────────────────────────────────────────────────────
info "Creating runtime directories..."
mkdir -p "$ROOT_DIR/data" "$ROOT_DIR/uploads" "$ROOT_DIR/backups"
chmod 700 "$ROOT_DIR/data"
chmod 755 "$ROOT_DIR/uploads" "$ROOT_DIR/backups"

# ── 5. nginx ──────────────────────────────────────────────────────────────────
if [ "$NGINX_AVAILABLE" = true ] && [ -n "${DOMAIN:-}" ]; then
  echo ""
  read -r -p "Configure nginx for $DOMAIN? [Y/n] " CONF_NGINX
  if [[ "$CONF_NGINX" != "n" && "$CONF_NGINX" != "N" ]]; then
    NGINX_CONF="/etc/nginx/sites-available/crash-site"
    NGINX_LINK="/etc/nginx/sites-enabled/crash-site"

    info "Writing nginx config to $NGINX_CONF..."
    sed "s/YOURDOMAIN/$DOMAIN/g" "$ROOT_DIR/nginx/crash-site.conf" \
      | sudo tee "$NGINX_CONF" > /dev/null

    if [ ! -L "$NGINX_LINK" ]; then
      sudo ln -s "$NGINX_CONF" "$NGINX_LINK"
    fi

    # Temporarily serve HTTP-only so certbot can complete the challenge
    # Replace SSL directives with a plain HTTP block for the initial nginx test
    sudo nginx -t 2>/dev/null && sudo systemctl reload nginx || {
      warn "nginx config test failed — check $NGINX_CONF"
    }

    if [ "$CERTBOT_AVAILABLE" = true ]; then
      echo ""
      read -r -p "Request SSL certificate for $DOMAIN via Certbot? [Y/n] " DO_CERT
      if [[ "$DO_CERT" != "n" && "$DO_CERT" != "N" ]]; then
        sudo certbot --nginx -d "$DOMAIN"
        sudo systemctl reload nginx
        info "SSL certificate installed."
      fi
    else
      warn "Certbot not found. To get SSL later: sudo certbot --nginx -d $DOMAIN"
    fi
  fi
else
  if [ "$NGINX_AVAILABLE" = false ]; then
    info "Skipping nginx setup (not installed)."
    info "After installing nginx, run:"
    info "  sed 's/YOURDOMAIN/$DOMAIN/g' nginx/crash-site.conf | sudo tee /etc/nginx/sites-available/crash-site"
    info "  sudo ln -s /etc/nginx/sites-available/crash-site /etc/nginx/sites-enabled/"
    info "  sudo certbot --nginx -d $DOMAIN"
  fi
fi

# ── 6. Build and start containers ────────────────────────────────────────────
echo ""
info "Building Docker containers (this may take a few minutes)..."
docker compose build --no-cache

info "Starting services..."
docker compose up -d --remove-orphans

# ── 7. Health check ───────────────────────────────────────────────────────────
info "Waiting for backend health check..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:4000/health > /dev/null 2>&1; then
    info "Backend is up."
    break
  fi
  if [ "$i" -eq 30 ]; then
    err "Backend did not start within 30 seconds."
    echo "  Check logs: docker compose logs backend"
    exit 1
  fi
  sleep 1
done

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "================================================"
info "Setup complete!"
echo ""
if [ -n "${DOMAIN:-}" ]; then
  echo "  Site:  https://${DOMAIN}"
fi
echo "  Logs:  docker compose logs -f"
echo "  Stats: ./scripts/db-stats.sh"
echo ""
echo "  For future deployments: ./scripts/deploy.sh"
echo "================================================"
echo ""
